export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const SET_USER_LOGIN_STATE = 'SET_USER_LOGIN_STATE';
export const SET_USER_INFO_STATE = 'SET_USER_INFO_STATE';
export const SET_ORGS_STATE = 'SET_ORGS_STATE';
